### REGISTER REQUEST
GET http://localhost:5100/api/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJBdXJlbGlhbiIsImxhc3ROYW1lIjoiR2FpdSIsImVtYWlsIjoiYXVyZWxpYW4uZ2FpdTExQGdtYWlsLmNvbSIsImlhdCI6MTU5MTIwNTk5Nn0.LRZD1NnZE31P-pNU-01OWc_g6px5O-tnKDedHothxw4
